### PR TITLE
MainActivity.kt: fixed app not handling links when not in background …

### LINKED ISSUE #678: Links only open after already having OuterTune open
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/OuterTune/OuterTune/actions) AND any logs I have attached are taken with the DEBUG version (NOT release).
- [x] I've checked that there is no open or closed issue about this bug. [CHECK THE ISSUE TRACKER HERE](https://github.com/OuterTune/OuterTune/issues)
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.
- [ ] I've checked these boxes without reading carefully.

### Steps to reproduce the bug

0. Have OuterTune configured to open music.youtube.com links
1. Open a YouTube Music link with OuterTune
2. (App opens, but doesn't handle the link)
3. Do it again
4. With the app open, it now handles the link

### Expected behavior

The link should be handled by the app when it is opened

### Actual behavior

The link only gets handled if the app was already open

### Screenshots/Screen recordings

_No response_

### Logs

_No response_

### OuterTune version

0.9.0 core 

### Device & Android version

Android 15

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by albertyeh199909**
…already

### What is it?

- [ ] New feature (user facing)
- [ ] Update to existing feature (user facing)
- [x] Bugfix (user facing)
- [ ] Codebase improvements or refactors (dev facing)
- [ ] Other

### Description of the changes in your PR

added a rememberSaveable as a flag variable to indicate if the initial intent has a URI that needs to be handled. 
Added LaunchedEffect(Unit) to call `youtubeNavigator` function to handle the URI once.

### Before/After Screenshots/Screen Record

- Before:
- After:

### Fixes the following issue(s)

- Fixes #678

## Due diligence

- [x] I have read and agreed to the [contribution guidelines](https://github.com/OuterTune/OuterTune/blob/dev/CONTRIBUTING.md).

### Merging strategy / Merge conflict resolution

Select only ONE. If you select none, or both, the first selection will used as your final choice

- [x] When merging this pull request, or in the event of merge conflicts, I give permission for the merger to rebase,
  or squash my code, or apply merge conflict amendments as needed
- [ ] When merging this pull request, or in the event of merge conflicts, I ***DO NOT*** give permission for the
  merger to modify my code to solve merge conflicts. I understand in the event of a merge conflict, I will be
  responsible to resolve merge conflicts in a way that adheres to
  the [contribution guidelines](https://github.com/OuterTune/OuterTune/blob/dev/CONTRIBUTING.md)

### CODE REVIEW

File: app/src/main/java/com/dd3boh/outertune/MainActivity.kt [hunk 1]
```diff
@@ -379,6 +381,14 @@ class MainActivity : ComponentActivity() {
             var themeColor by rememberSaveable(stateSaver = ColorSaver) {
                 mutableStateOf(DefaultThemeColor)
             }
+            //Getting song from deep link when app is not running does not work otherwise
+            var getSongOnLaunch by rememberSaveable{
+                if (initIntentUri != null) {
+                    mutableStateOf(true)
+                } else {
+                    mutableStateOf(false)
+                }
```
Comment (mikooomich) [inline app/src/main/java/com/dd3boh/outertune/MainActivity.kt]: mutableStateOf(initIntentUri != null)

File: app/src/main/java/com/dd3boh/outertune/MainActivity.kt [hunk 2]
```diff
@@ -760,6 +770,13 @@ class MainActivity : ComponentActivity() {
                         }
                     )
 
+                    LaunchedEffect(Unit) {
+                        if(getSongOnLaunch && initIntentUri != null) {
```
Comment (mikooomich) [inline app/src/main/java/com/dd3boh/outertune/MainActivity.kt]: `if(` -> `if (`


You can just use the Android Studio auto formater. We use the default settings, aside from line breaks which are about at 120 chars

**Review by mikooomich — CHANGES_REQUESTED** [review]

**Comment by mikooomich** [comment]
Hello, it works nicely thank you!

I think you can just do it all in the launched effect?
```
                    LaunchedEffect(Unit) {
                        var initIntentUri = intent.data ?: intent.extras?.getString(Intent.EXTRA_TEXT)?.toUri()
                        if (initIntentUri != null) {
                            youtubeNavigator(initIntentUri)
                        }
                    }
```

**Comment by albertyeh199909** [comment]
> Hello, it works nicely thank you!
> 
> I think you can just do it all in the launched effect?
> 
> ```
>                     LaunchedEffect(Unit) {
>                         var initIntentUri = intent.data ?: intent.extras?.getString(Intent.EXTRA_TEXT)?.toUri()
>                         if (initIntentUri != null) {
>                             youtubeNavigator(initIntentUri)
>                         }
>                     }
> ```

Oh you're right. In hindsight that was pretty obvious. My bad. I removed the unnecessary rememberSaveable.
