### PR TITLE
Retry on play fail and no connection

### LINKED ISSUE #181: Skipping songs without touching the next button
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/dd3boh/OuterTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Pick a song
2. Then this will appear Playback error: source error (2004): Response code:403
3. The next song will automatically play. 

### Expected behavior

This should only happen when the next button is pressed. 

### Actual behavior

This happened without hitting the next button. 

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8dab8241-c129-4976-acb1-c39d2bdbe73e

### Logs

This issue is easy to reproduce. 

### OuterTune version

0.6.4

### Device & Android version

Honor phone, Android 14

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mattcarter11**
#### What is it?
- [ ] New feature (user facing)
- [x] Update to existing feature (user facing)
- [ ] Bugfix (user facing)
- [ ] Translations
- [ ] Codebase improvements or refactors (dev facing)
- [ ] Other

#### Description of the changes in your PR

- add logic to handle error when no connection
- expose flag when player is waiting for connection
- add logic to resume playing on connection
- add error message when this happens

Closes #181 

#### Due diligence
- [x] I read the [contribution guidelines](../CONTRIBUTING.md).
- [x] I understand that in the event of merge conflicts, **I may be asked to rebase my branch** on top of the dev branch, instead of resolving them by merging dev into my own branch

### CODE REVIEW

**Comment by mattcarter11** [comment]
@mikooomich conflicts fixed

File: app/src/main/java/com/dd3boh/outertune/constants/PreferenceKeys.kt [hunk 1]
```diff
@@ -46,7 +46,6 @@ val AudioOffload = booleanPreferencesKey("enableOffload")
 
 val PersistentQueueKey = booleanPreferencesKey("persistentQueue")
 val SkipSilenceKey = booleanPreferencesKey("skipSilence")
-val SkipOnErrorKey = booleanPreferencesKey("skipOnError")
```
Comment (mikooomich) [inline app/src/main/java/com/dd3boh/outertune/constants/PreferenceKeys.kt]: Why remove this key? skipOnError on: auto skip is on. skipOnError off: pause on error

File: app/src/main/java/com/dd3boh/outertune/playback/MusicService.kt [hunk 2]
```diff
@@ -213,6 +216,20 @@ class MusicService : MediaLibraryService(),
             }
         }
 
+        networkConnectivityObserver = NetworkConnectivityObserver(this)
```
Comment (mikooomich) [inline app/src/main/java/com/dd3boh/outertune/playback/MusicService.kt]: Should probably use the same connectivity observer from main activity?

File: app/src/main/java/com/dd3boh/outertune/utils/Retry.kt [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    functionName: String,
+    block: suspend () -> T
+): T {
+    var currentDelay = initialDelay
+    repeat(times - 1) { attempt ->
+        try {
+            return block()
+        } catch (e: Throwable) {
+            val nextDelay = currentDelay + Random.nextLong(0, jitterRange)
+            Timber.tag("Retry").d("$functionName attempt ${attempt + 1} of $times failed, retrying in $nextDelay ms")
```
Comment (mikooomich) [inline app/src/main/java/com/dd3boh/outertune/utils/Retry.kt]: I think tagging with "NetworkUtils" or something would be a better tag

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -207,6 +207,9 @@
     <string name="error_no_internet">No network connection</string>
     <string name="error_timeout">Timeout</string>
     <string name="error_unknown">Unknown error</string>
+    <string name="on_error">On error</string>
+    <string name="pause">Pause</string>
```
Comment (mikooomich) [inline app/src/main/res/values/strings.xml]: Both the notification stuff in music service and these strings are removed or moved to another file respectively. I'll can fix these 2 and then just squash merge in the end.


As always, thanks for your work!

**Review by mikooomich — CHANGES_REQUESTED** [review]

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (mattcarter11) [reply app/src/main/res/values/strings.xml]: Ok, move them where they should be

File: app/src/main/java/com/dd3boh/outertune/playback/MusicService.kt (hunk 2 above)
Comment (mattcarter11) [reply app/src/main/java/com/dd3boh/outertune/playback/MusicService.kt]: how?
